apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- namespace.yaml
- service.yaml
namespace: toptips
commonLabels:
  app.kubernetes.io/framework: spring-boot-2.4
configMapGenerator:
  - name: spring-application-config
    files:
      - application.yaml
secretGenerator:
  - name: user-creds
    literals:
      - username=alice
      - password=test
